platform :ios, '13.0'
inhibit_all_warnings!

target 'AFOPlayer' do
  pod 'AFOGitHub'
  pod 'AFODelegateExtension'
  pod 'AFOLANUpload', :path => '../../AFOLANUpload'
  pod 'AFOPlaylist'
  pod 'AFOOnlinePlay', :git => 'https://github.com/PangDuTechnology/AFOOnlinePlay.git', :tag => '0.0.2'
  pod 'AFOFFMpeg'
  pod 'AFOFoundation'
  pod 'AFORouter'
  pod 'AFOSchedulerCore'
  pod 'AFOUIKIT'
  pod 'AFOViews'
end

post_install do |installer|
  simulator_ldflags = [
    '$(inherited)',
    '-ObjC',
    '-lAFODelegateExtension',
    '-lAFOLANUpload',
    '-lAFOFoundation',
    '-lAFOGitHub',
    '-lAFOPlaylist',
    '-lAFOOnlinePlay',
    '-lAFORouter',
    '-lAFOSQLite',
    '-lAFOSchedulerCore',
    '-lAFOUIKIT',
    '-lAFOViews',
    '-lFMDB',
    '-liconv',
    '-lsqlite3',
    '-lz'
  ]

  iphoneos_ldflags = [
    '$(inherited)',
    '-ObjC',
    '-lAFODelegateExtension',
    '-lAFOLANUpload',
    '-lAFOFFMpeg',
    '-lAFOFoundation',
    '-lAFOGitHub',
    '-lAFOPlaylist',
    '-lAFOOnlinePlay',
    '-lAFORouter',
    '-lAFOSQLite',
    '-lAFOSchedulerCore',
    '-lAFOUIKIT',
    '-lAFOViews',
    '-lFMDB',
    '-lSDWebImage',
    '-lavcodec',
    '-lavformat',
    '-lavutil',
    '-lbz2',
    '-lc',
    '-lc++',
    '-liconv',
    '-lsqlite3',
    '-lswresample',
    '-lswscale',
    '-lx264',
    '-lxvidcore',
    '-lyuv',
    '-lz',
    '-framework AVFoundation',
    '-framework AudioToolbox',
    '-framework CoreGraphics',
    '-framework CoreImage',
    '-framework CoreMedia',
    '-framework OpenGLES',
    '-framework VideoToolbox'
  ]

  installer.pods_project.targets.each do |target|
    next unless target.name == 'Pods-AFOPlayer'

    target.build_configurations.each do |config|
      config.build_settings['OTHER_LDFLAGS[sdk=iphonesimulator*]'] = simulator_ldflags
      config.build_settings['OTHER_LDFLAGS[sdk=iphoneos*]'] = iphoneos_ldflags
    end
  end
end
