platform :ios, '13.0'
inhibit_all_warnings!

target 'AFOPlayer' do
  pod 'AFOGitHub',:path =>'../../AFOGitHub'
  pod 'AFODelegateExtension',:path => '../../AFODelegateExtension'
  pod 'AFOPlaylist', :path => '../../AFOPlaylist'
  pod 'AFOFFMpeg', :path => '../../AFOFFMpeg'
  pod 'AFOFoundation', :path => '../../AFOFoundation'
  pod 'AFORouter', :path => '../../AFORouter'
  pod 'AFOSchedulerCore', :path => '../../AFOSchedulerCore'
  pod 'AFOUIKIT',:path => '../../AFOUIKIT'
  pod 'AFOViews',:path => '../../AFOViews'
end
